name: cd
on:
  workflow_call:
    inputs:
      overlay_path:
        required: false
        type: string
        default: homelab
      environment:
        required: false
        type: string
        default: Homelab

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2

      - name: Tailscale
        uses: tailscale/github-action@v1
        timeout-minutes: 5
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - uses: imranismail/setup-kustomize@v1

      - run: |
          kustomize build ${{ inputs.overlay_path }} -o kubernetes.yaml

      - name: kubectl apply
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f kubernetes.yaml