name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      registry:
        required: true
        type: string
      platforms:
        required: false
        type: string
        default: linux/amd64,linux/arm64
      dockerfile:
        required: false
        type: string
        default: Dockerfile
      version_file:
        required: false
        type: string
        default: version.txt

jobs:
  build_push_docker_image:
    permissions:
      contents: write   # needed to push git tags
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Read version from file
        id: read_version
        run: |
          VERSION=$(cat ${{ inputs.version_file }} | tr -d ' \n')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.REPOSITORY_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ inputs.registry }}/${{ inputs.image }}
          tags: |
            type=sha,format=long
            type=ref,event=tag

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.4.0

      - name: Build and publish Docker image
        id: build-and-publish
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          platforms: ${{ inputs.platforms }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ inputs.registry }}/${{ inputs.image }}:${{ steps.read_version.outputs.version }}

      - name: Create Git tag with version
        if: ${{ steps.read_version.outputs.version != '' }}
        env:
          VERSION: ${{ steps.read_version.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git tag -a "v$VERSION" -m "Release version $VERSION"
          git push origin "v$VERSION"
