name: build push sign
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      registry:
        required: true
        type: string
      environment:
        required: false
        type: string
        default: Homelab
      platforms:
        required: false
        type: string
        default: linux/amd64,linux/arm64
      dockerfile:
        required: false
        type: string
        default: Dockerfile
      tags:
        description: 'Comma-separated list of tags'
        type: string
        required: false
jobs:
  build_push_sign:
    permissions:
      packages: write
      id-token: write
    name: build-push-sign
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: log in to ghcr
        uses: docker/login-action@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.REPOSITORY_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ inputs.registry }}/${{ inputs.image }}
          tags: |
            type=sha,format=long
            latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: build and publish image
        id: build-and-publish
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          platforms: ${{ inputs.platforms }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}

      - name: Install Cosign
        if: ${{ github.event_name != 'pull_request' }}
        uses: sigstore/cosign-installer@v3.4.0

      - name: sign
        if: ${{ github.event_name != 'pull_request' }}
        run: cosign sign --yes "${TAGS}@${DIGEST}"
        env:
          DIGEST: ${{ steps.build-and-publish.outputs.digest }}
          TAGS: ${{ steps.meta.outputs.tags }}
