name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      platforms:
        required: false
        type: string
        default: linux/amd64,linux/arm64
      dockerfile:
        required: false
        type: string
        default: Dockerfile

jobs:
  build_push_docker_image:
    permissions:
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Build and publish Docker image
        id: build-and-publish
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: false
          platforms: ${{ inputs.platforms }}