name: Release Helm Charts

on:
  workflow_call:
    inputs:
      publish_oci:
        description: "Publish charts to OCI registry in addition to chart-releaser"
        required: false
        default: false
        type: boolean
      oci_registry:
        description: "OCI registry to publish charts to"
        required: false
        default: "ghcr.io"
        type: string
      charts_dir:
        description: "Directory containing helm charts"
        required: false
        default: "charts"
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v5

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Login to OCI Registry
        if: ${{ inputs.publish_oci }}
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.oci_registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and Push Chart to OCI
        if: ${{ inputs.publish_oci }}
        env:
          CHARTS_DIR: ${{ inputs.charts_dir }}
          OCI_REGISTRY: ${{ inputs.oci_registry }}
        run: |
          helm package "$CHARTS_DIR" --destination /tmp/
          helm push /tmp/*.tgz "oci://$OCI_REGISTRY/${{ github.repository_owner }}/charts"
