name: Release Please

on:
  workflow_call:
jobs:
  release_please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Release Please
        uses: googleapis/release-please-action@v4
        env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          release-type: simple
