name: Test OCI Publish

on:
  push:
    branches:
      - feature/oci-publish

jobs:
  # publish:
  #   uses: ./.github/workflows/helm-publish-oci.yml
  #   with:
  #     charts_dir: charts/test-chart

  release:
    uses: ./.github/workflows/helm-release.yml
    with:
      charts_dir: charts/test-chart
      publish_oci: true
